import type { Metadata } from "next";
import "./globals.css";
import { TasksContextProvider } from "@/contexts/taskContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <TasksContextProvider>
        {children}
        </TasksContextProvider>
      </body>
    </html>
  );
}
